---
title: "TitanicEDA"
output:
  html_document:
    df_print: paged
---


```{r Created dataframe}
# Created a titanic_data dataframe from csv file 
titanic_data <-read.csv("cleaned_titanic_data.csv")
```

hi 
```{r Installed and attached necessary packages}
# Installed and attached necessary packages
install.packages("tidyverse")
install.packages("plotly")
library(tidyverse)
library(plotly)
```

```{r Bar Plot of survived}
# Bar Plot of survived
ggplot(titanic_data, aes(x=as.factor(survived))) +
geom_bar(fill="purple") +
xlab("survived") +
ylab("count") +
ggtitle("Count of Survived Passengers on the Titanic")
```

```{r Histogram of Age}
# Histogram of Age
ggplot(titanic_data, aes(x = age)) +
  geom_histogram(binwidth = 5, fill = "orange", color = "black") +
  xlab("Age") +
  ylab("Count") +
  ggtitle("Age Distribution of Passengers")
```

```{r Box Plot of Age by Survived}
# Box Plot of Age by Survived
ggplot (titanic_data, aes(x = as.factor(survived), y = age)) +
  geom_boxplot(fill="purple") +
  xlab("Survived") +
  ylab("Age") +
  ggtitle("Age Distribution by Survival Status")
```

```{r Bar Plot of Passenger Class}
# Bar Plot of Passenger Class
ggplot(titanic_data, aes(x = as.factor(pclass))) +
  geom_bar(fill = "blue") +
  xlab("Passenger Class") +
  ylab("Count") +
  ggtitle("Count of Passengers by Class")
```

```{r Bar Plot of Embarked}
# Bar Plot of Embarked
ggplot(titanic_data, aes(x = embarked)) +
  geom_bar(fill = "black") +
  xlab("Embarkation Point") +
  ylab("Count") +
  ggtitle("Count of Passengers by Embarkation Point")
```

```{r Scatter Plot of Age vs. Fare}
# Scatter Plot of Age vs. Fare
ggplot(titanic_data, aes(x = age, y = fare)) +
  geom_point(color = "blue") +
  xlab("Age") +
  ylab("Fare") +
  ggtitle("Scatter Plot of Age vs. Fare")
```

```{r Facet Grid of Age vs. Fare by Survived}
# Facet Grid of Age vs. Fare by Survived
ggplot(titanic_data, aes(x = age, y = fare)) +
  geom_point(color="orange") +
  facet_grid(. ~ survived) +
  xlab("Age") +
  ylab("Fare") +
  ggtitle("Age vs. Fare by Survival Status")
```

